wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699863092.701872
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 7
      - 13
      - 23
      4: 3.11.6
      5: 0.15.12
      8:
      - 3
      - 8
      13: windows-amd64
    m:
    - 1: custom_step
      6:
      - 3
